{{- if .Values.panel.jaeger.enabled -}}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: panel-otel-instrumentation
  namespace: {{ .Release.Namespace }}
spec:
  exporter:
    endpoint: http://panel-otel-collector.{{ .Release.Namespace }}.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
    - jaeger
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  imagePullPolicy: IfNotPresent
{{- end -}}