{{- if .Values.panel.jaeger.gateway.enabled -}}
{{- $jaegerImageTag := last (regexSplit ":" (tpl .Values.panel.jaeger.image .) -1) -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: panel-otel-collector-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    "org.mlodzirazem.panel.component": "jaeger-otel-collector"
    "org.mlodzirazem.panel.layer": "observability"
spec:
  gatewayClassName: {{ tpl (.Values.panel.jaeger.gateway.gatewayClass | default .Values.panel.gateway.gatewayClass) . }}
  listeners:
    - name: jaeger-listener
      port: {{ .Values.panel.jaeger.gateway.port }}
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: panel-otel-collector-route
  namespace: {{ .Release.Namespace }}
  labels:
    "org.mlodzirazem.panel.component": "jaeger-otel-collector"
    "org.mlodzirazem.panel.layer": "observability"
spec:
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: panel-otel-collector
          port: 16686
{{- end -}}