# Use this file for rendering YAML

panel:
  secrets:
    panel:
      web:
        metricsToken: metrics-token
        nextauthToken: nextauth-token
    postgres:
      database: mrpanel
      admin:
        username: pg-user
        password: pg-password
      panel:
        username: mrpanel-pg-user
        password: mrpanel-pg-password
    google:
      oauth:
        clientId: google-clientId
        clientSecret: google-clientSecret
      workspace:
        accountToken: google-workspace-accountToken
    smtp:
      host: smtp.mlodzirazem.org
      port: 587
      username: smpt-user
      password: smtp-password
    cloudflare:
      apiKey: cloudflare-apiKey