{{- if not (dig "cnpg" "install" false .Values.panel.postgres) -}}

apiVersion: v1
kind: Secret
metadata:
  name: panel-api-postgres-credentials
  namespace: {{ .Release.Namespace }}
  labels: {{ include "panel-api.labels" . | nindent 4 }}
data:
  username: {{ .Values.panel.postgres.cnpg.users.mrpanel.username | b64enc | quote }}
  password: {{ .Values.panel.postgres.cnpg.users.mrpanel.password | b64enc | quote }}
{{- end -}}