apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: panel-web
  namespace: {{ .Release.Namespace }}
  labels: {{ include "panel-web.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
    - portNumber: 3000
      interval: 60s
      scrapeTimeout: 15s
      path: /metrics
      enableHttp2: true
      authorization:
        type: Bearer
        credentials:
          key: metrics-auth-token
          name: panel-web-secret
  selector:
    matchLabels: {{ include "panel-web.labels" . | nindent 6 }}