apiVersion: v1
kind: Service
metadata:
  name: panel-web
  namespace: {{ .Release.Namespace }}
  labels: {{ include "panel-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.panel.web.service.type }}
{{- if .Values.panel.web.service.loadBalancerClass}}
  loadBalancerClass: {{ tpl .Values.panel.web.service.loadBalancerClass . }}
{{- end }}
  ports:
    - port: 3000
      name: http
      protocol: TCP
  selector:
    {{- include "panel-web.labels" . | nindent 4 }}