apiVersion: v1
kind: Secret
metadata:
  name: panel-web-secret
  namespace: {{ .Release.Namespace }}
  labels: {{ include "panel-web.labels" . | nindent 4 }}
data:
  metrics-auth-token: {{ tpl .Values.panel.secrets.panel.web.metricsToken . | b64enc | quote }}
  nextauth-secret: {{ tpl .Values.panel.secrets.panel.web.nextauthToken . | b64enc | quote }}
  panel-web-google-client-id: {{ tpl .Values.panel.secrets.google.oauth.clientId . | b64enc | quote }}
  panel-web-google-client-secret: {{ tpl .Values.panel.secrets.google.oauth.clientSecret . | b64enc | quote }}