{{- if .Values.panel.gateway.install -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: panel-cloudflare-api-token
  labels: {{ include "gateway.labels" . | nindent 4 }}
data:
  token: {{ tpl .Values.panel.secrets.cloudflare.apiKey . | b64enc | quote }}
{{- end -}}