{{- if .Values.panel.gateway.install -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: panel-web-httproute
  namespace: {{ .Release.Namespace }}
  labels: {{ include "gateway.labels" . | nindent 4 }}
spec:
  hostnames: {{ tpl (.Values.panel.gateway.domains | toJson) . }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: panel-web
          port: 3000
          group: ""
          kind: Service
          namespace: {{ .Release.Namespace }}
{{- end -}}