{{- if .Values.panel.gateway.install -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: panel-gateway
  namespace: {{ .Release.Namespace }}
  labels: {{ include "gateway.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ tpl .Values.panel.gateway.gatewayClass . | quote }}
  listeners:
    - name: panel-web
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: panel-ssl-cert
            namespace: {{ .Release.Namespace }}
            group: ""
{{- end -}}