{{- if .Values.panel.postgres.cnpg.install -}}
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-user-secret
  namespace: {{ .Release.Namespace }}
  labels:
    cnpg.io/reload: "true"
data:
  username: {{ .Values.panel.postgres.cnpg.users.mrpanel.username | b64enc | quote }}
  password: {{ .Values.panel.postgres.cnpg.users.mrpanel.password | b64enc | quote }}
type: kubernetes.io/basic-auth
{{- end -}}