name: Build and test all when needed
on:
  push:
    branches:
      - master
      - develop
  merge_group:
    types:
      - checks_requested
jobs:
  compileAndTest:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: temurin
          architecture: x64
          cache: maven
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots --also-make --also-make-dependents clean install
---
name: Build and test panel-api
on:
  push:
    paths:
      - services/panel-api/**
jobs:
  compileAndTest:
    uses: ./.github/workflows/build-directory.yaml
    with:
      directory: services/panel-api
---
name: Build and test panel-web
on:
  push:
    paths:
      - services/panel-web/**
jobs:
  compileAndTest:
    uses: ./.github/workflows/build-directory.yaml
    with:
      directory: services/panel-web
---
name: Build and test docs
on:
  push:
    paths:
      - docs/**
jobs:
  compileAndTest:
    uses: ./.github/workflows/build-directory.yaml
    with:
      directory: docs
---
name: Build and test cloud
on:
  push:
    paths:
      - cloud/**
jobs:
  compileAndTest:
    uses: ./.github/workflows/build-directory.yaml
    with:
      directory: cloud